version: '3.5'

services: 
    mongodb:
        container_name: mongodb_container
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example      
        volumes:
            - mongodbvolume:/data/db
        ports: 
            - 27017:27017
        networks:
            - mongodb
        restart: unless-stopped

networks: 
    mongodb:
        driver: bridge
volumes: 
    mongodbvolume: